### ISSUE TITLE
Vue Ajax Requests With Axios ? 

### ISSUE THREAD

**Issue by majianxiong** [platojs/plato#53]
![image](https://cloud.githubusercontent.com/assets/887531/23783112/f0d4f37e-0593-11e7-958f-3966182129cf.png)
为何不考虑集成一下Axios呢 [Retiring vue-resource](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.wt58qc40p)

**Comment by kagawagao** [comment]
考虑未来的 API 标准，所以使用了 `fetch` ([规范](https://fetch.spec.whatwg.org/))，但是这都是自选的，和 `Vue` 一样，这同样是一个渐进式的框架，你可以自由选择配套设施，比如说 `Axios`。

当然具体说明还需要 @crossjs 来解答一下

**Comment by majianxiong** [comment]
@kagawagao 恩，但是目前好像在Web前端开发中这个接口使用的不是很多

**Comment by crossjs** [comment]
fetch 比 axios 优雅、轻量；高版本浏览器原生支持 fetch。

因为 PLATO 主要的目标是移动端，所以我们在库的选择上，都倾向于选择轻量的、符合未来标准的（意味着等到兼容性上来后，可以把 polyfill 移除，这样我们的代码就可以更轻）。
