### ISSUE TITLE
Error retrieving a new session from the selenium server

### ISSUE THREAD

**Issue by majianxiong** [platojs/plato#58]
执行 npm test 报以下错误
`
> PLATO@3.0.0-beta.11 e2e G:\Developer\IDEA\bipolar\plato
> cross-env NODE_ENV=test DEBUG=PLATO:* node ./test/e2e/runner.js

  PLATO:config Create configuration. +0ms
  PLATO:config Apply environment overrides for NODE_ENV "test". +2ms
  PLATO:webpack Create configuration. +47ms
  PLATO:webpack Enable plugins for live development (HMR, NoErrors). +9ms
Starting server on http://127.0.0.1:3000
Starting selenium server... started - PID:  19568

[Test] Test Suite
=====================

Running:  default e2e tests

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ state: 'unhandled error',
  sessionId: null,
  hCode: 2032408365,
  value:
   { additionalInformation: '\nDriver info: org.openqa.selenium.chrome.ChromeDriver',
……
`

**Comment by majianxiong** [comment]
`
{ additionalInformation: '\nDriver info: org.openqa.selenium.chrome.ChromeDriver',
     localizedMessage: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.28.455520 (cc17746adff549
84afff480136733114c6b3704b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace i
nformation)\nCommand duration or timeout: 690 milliseconds\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time:
\'2016-06-30 17:37:03\'\nSystem info: host: \'LS-300441\', ip: \'192.168.0.102\', os.name: \'Windows 7\', os.arch: \'amd64
\', os.version: \'6.1\', java.version: \'1.8.0_111\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver',
     systemInformation: 'System info: host: \'LS-300441\', ip: \'192.168.0.102\', os.name: \'Windows 7\', os.arch: \'amd64
\', os.version: \'6.1\', java.version: \'1.8.0_111\'',
     supportUrl: null,
     cause: null,
     suppressed: [],
     message: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.28.455520
`
需要安装Google chrome 浏览器吗

**Comment by majianxiong** [comment]
安装了Chrome浏览器就可以了

**Comment by crossjs** [comment]
谢谢反馈，我会在文档里注明。
