### ISSUE TITLE
基础注册模块分离

### ISSUE THREAD

**Issue by majianxiong** [platojs/plato#62]
![image](https://cloud.githubusercontent.com/assets/887531/25067519/f1987b76-2278-11e7-9ab8-fbdff564d325.png)

核心模块的注册是否考虑在[System](https://github.com/platojs/system)中进行默认注册

**Comment by crossjs** [comment]
对此 Repo 来说是核心模块，对 System 来说却不是。
这两个功能，在不同的需求场景下，可以有不一样的实现方式。
