### ISSUE TITLE
输入一个不正确的地址404

### ISSUE THREAD

**Issue by majianxiong** [platojs/plato#65]
输入一个错误的地址，变成404
![image](https://cloud.githubusercontent.com/assets/887531/25770578/81f60d76-326b-11e7-97bb-1f668fb63549.png)
https://github.com/codecasts/spa-starter-kit/tree/develop/client
似乎不会有这个问题，唯一的区别就是webpack-dev-server和Express

**Comment by majianxiong** [comment]
改成利用 [vuejs-templates](https://github.com/vuejs-templates/webpack) 就可以了

**Comment by crossjs** [comment]
因为 github pages 默认不支持 h5 的 history fallback rewrite
